# Generated by Django 5.2 on 2025-04-11 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univers', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=100)),
                ('illustration', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='perso',
            field=models.ManyToManyField(to='dashboard.personnage'),
        ),
    ]
