# Generated by Django 5.2 on 2025-04-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('game_type', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('Platformer', 'Platformer'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Other', 'Other')], max_length=50)),
                ('ambiance', models.TextField()),
                ('graphic_style', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GamePitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('target_audience', models.CharField(max_length=200)),
                ('gameplay_mechanics', models.TextField()),
                ('platforms', models.CharField(max_length=200)),
                ('business_model', models.CharField(max_length=200)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('universe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to='dashboard.gameuniverse')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='concepts/')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_arts', to='dashboard.gameuniverse')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('abilities', models.TextField()),
                ('motivation', models.TextField()),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dashboard.gameuniverse')),
            ],
        ),
        migrations.CreateModel(
            name='MainStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('structure', models.TextField(help_text='Décris ici les arcs narratifs, les chapitres, les rebondissements...')),
                ('universe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='dashboard.gameuniverse')),
            ],
        ),
    ]
