# Generated by Django 5.2 on 2025-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='illustration',
            field=models.CharField(max_length=300),
        ),
    ]
