# Generated by Django 5.2 on 2025-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gameuniverse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuniverse',
            name='game_type',
            field=models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('Platformer', 'Plateforme'), ('Adventure', 'Aventure'), ('Horror', 'Horreur'), ('Other', 'Autre')], max_length=50),
        ),
    ]
