# Generated by Django 5.2 on 2025-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_game_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='illustration',
            field=models.TextField(),
        ),
    ]
