# Generated by Django 5.2 on 2025-04-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_game_illustration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='perso',
        ),
    ]
